### ISSUE TITLE
"Trying to join call" hangs forever

### ISSUE THREAD

**Issue by mitchellh** [hubot-archive/hubot-google-hangouts#5]
I don't think the new URL structure works at all unfortunately. I've tried even doing it manually and whenever I create a hangout it just hangs for myself and others on "Trying to join call". I've verified I'm trying to join as the same domain, even.

**Comment by stonith** [comment]
I tried digging into the same thing a few weeks ago and gave up. It looks like Google changed their integration, a person can initiate a hangout via https://hangouts.google.com/start as per #4 but a random generated link is then created. Slack seems to handle this with their Hangouts "app" that posts the generated link back to the channel.

**Comment by alindeman** [comment]
Closing to focus on #4
